version: '3.7'

services:     
  mariadb:
    container_name: 11_web-mariadb
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: webdb
      MARIADB_USER: webdb
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:5111:3306"
      
  web:
    container_name: 11_calculator
    hostname: app
    build: 11_Calculator/
    ports:
      - "0.0.0.0:5011:5011"
