// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payments.Data;

#nullable disable

namespace Payments.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240311131725_test1")]
    partial class test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("Payments.Models.DataInvoicesPay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DatePayment")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateScore")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayPay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdClient")
                        .HasColumnType("INTEGER");

                    b.Property<double>("IdPayment")
                        .HasColumnType("REAL");

                    b.Property<double>("IdScore")
                        .HasColumnType("REAL");

                    b.Property<int>("Kod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Sum")
                        .HasColumnType("REAL");

                    b.Property<double>("SumPayment")
                        .HasColumnType("REAL");

                    b.Property<double>("SumScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ViewPayment")
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewScore")
                        .HasColumnType("TEXT");

                    b.Property<int>("payCondition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DataInvoicesPays");
                });

            modelBuilder.Entity("Payments.Models.InitialData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConditionPay")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateDoc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdKod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KodClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberDoc")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Sum")
                        .HasColumnType("REAL");

                    b.Property<string>("ViewDoc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InitialDates");
                });
#pragma warning restore 612, 618
        }
    }
}
